# Generated by Django 2.1 on 2018-09-24 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('account_type', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agencie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=40)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Blocked'), (4, 'Suspended'), (5, 'Spam')], default=1)),
                ('package', models.IntegerField(choices=[(1, 'Free'), (2, 'Silver'), (3, 'Gold')], default=1)),
                ('address', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('image_logo', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('duser', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=60)),
                ('website', models.CharField(max_length=255)),
                ('gps_longitude', models.CharField(max_length=50, null=True)),
                ('gps_latitude', models.CharField(max_length=50, null=True)),
                ('twitter', models.TextField(null=True)),
                ('facebook', models.TextField(null=True)),
                ('pintrest', models.TextField(null=True)),
                ('skype', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=40)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Blocked'), (4, 'Suspended'), (5, 'Spam')], default=1)),
                ('package', models.IntegerField(choices=[(1, 'Free'), (2, 'Silver'), (3, 'Gold')], default=1)),
                ('duser', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('image_logo', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('phone', models.CharField(max_length=255)),
                ('mobile_number', models.TextField(null=True)),
                ('prop_number', models.TextField(null=True)),
                ('email', models.EmailField(max_length=60)),
                ('website', models.CharField(max_length=255)),
                ('gps_longitude', models.CharField(max_length=50, null=True)),
                ('gps_latitude', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('account_status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Blocked'), (4, 'Suspended'), (5, 'Spam')], default=2)),
                ('phone_number', models.TextField(null=True)),
                ('mobile_number', models.TextField(null=True)),
                ('prop_number', models.TextField(null=True)),
                ('email_address', models.EmailField(max_length=50, null=True)),
                ('street_address', models.CharField(max_length=50)),
                ('profile_photo', models.TextField(null=True)),
                ('twitter', models.TextField(null=True)),
                ('facebook', models.TextField(null=True)),
                ('pintrest', models.TextField(null=True)),
                ('skype', models.TextField(null=True)),
                ('bio', models.TextField(null=True)),
                ('agency', models.ForeignKey(on_delete=None, to='kupeza.Agencie')),
                ('duser', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('subcomment', models.BooleanField(default=False)),
                ('prop_id', models.IntegerField()),
                ('user_id', models.IntegerField(null=True)),
                ('comm_id', models.IntegerField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ordinaryuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('account_status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Blocked'), (4, 'Suspended'), (5, 'Spam')], default=2)),
                ('phone_number', models.TextField(null=True)),
                ('mobile_number', models.TextField(null=True)),
                ('prop_number', models.TextField(null=True)),
                ('email_address', models.EmailField(max_length=50, null=True)),
                ('street_address', models.CharField(max_length=50)),
                ('profile_photo', models.TextField(null=True)),
                ('twitter', models.TextField(null=True)),
                ('facebook', models.TextField(null=True)),
                ('pintrest', models.TextField(null=True)),
                ('skype', models.TextField(null=True)),
                ('duser', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pricesdecrease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pricesincrease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.IntegerField(blank=True, null=True)),
                ('agent', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('currency', models.CharField(choices=[('K', 'Kwacha'), ('$', 'Dollars')], default='K', max_length=20)),
                ('property_price', models.IntegerField()),
                ('number_of_bedrooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('number_of_garages', models.IntegerField()),
                ('area_dimension', models.IntegerField()),
                ('payment_options', models.CharField(choices=[('Cash', 'Cash'), ('Debit', 'Debit')], max_length=50)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Flat', 'Flat'), ('Farm', 'Farm')], default='House', max_length=15)),
                ('property_status', models.CharField(choices=[('For Rent', 'For Rent'), ('For Sell', 'For Sell')], default='For Sell', max_length=20)),
                ('listing_status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('requested_price', models.IntegerField(null=True)),
                ('offered_price', models.IntegerField(null=True)),
                ('gps_longitude', models.CharField(max_length=50, null=True)),
                ('gps_latitude', models.CharField(max_length=50, null=True)),
                ('year_of_construction', models.DateField(null=True)),
                ('renovated_year', models.DateField(null=True)),
                ('house_plan_file', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255, null=True)),
                ('province', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('town', models.TextField(null=True)),
                ('tags', models.TextField(null=True)),
                ('ord_user', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=None, to='kupeza.Countrie')),
            ],
        ),
        migrations.CreateModel(
            name='Surburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surburb_name', models.CharField(max_length=60)),
                ('district', models.ForeignKey(on_delete=None, to='kupeza.District')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=None, to='kupeza.Province'),
        ),
    ]
